#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    DO \$\$
    BEGIN
       IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '$SUBSCRIPTIONS_USER') THEN
          CREATE USER $SUBSCRIPTIONS_USER WITH PASSWORD '$SUBSCRIPTIONS_PASSWORD' NOCREATEDB NOCREATEROLE;
       END IF;
    END
    \$\$;

    SELECT 'CREATE DATABASE $SUBSCRIPTIONS_DB OWNER $POSTGRES_USER'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$SUBSCRIPTIONS_DB')\gexec

    \c $SUBSCRIPTIONS_DB

    ALTER SCHEMA public OWNER TO $POSTGRES_USER;

    REVOKE ALL ON SCHEMA public FROM PUBLIC;

    GRANT USAGE ON SCHEMA public TO $SUBSCRIPTIONS_USER;
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO $SUBSCRIPTIONS_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $SUBSCRIPTIONS_USER;

    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO $SUBSCRIPTIONS_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO $SUBSCRIPTIONS_USER;

    REVOKE CREATE ON SCHEMA public FROM $SUBSCRIPTIONS_USER;

    DO \$\$
    DECLARE
        tbl text;
    BEGIN
        FOR tbl IN (SELECT tablename FROM pg_tables WHERE schemaname = 'public') LOOP
            EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON %I TO $SUBSCRIPTIONS_USER', tbl);
        END LOOP;
    END;
    \$\$;
EOSQL
